### ISSUE TITLE
Unable to install package due to version incompability reasons

### ISSUE THREAD

**Issue by attex** [Robert3141/client_server_lan#11]
Hi there,

i am getting the following error message:

Because every version of flutter_test from sdk depends on meta 1.3.0-nullsafety.3 and client_server_lan >=2.0.1 depends on meta ^1.3.0, flutter_test from sdk is incompatible with client_server_lan >=2.0.1

Has anyone ever experienced this?

Kind regards

**Comment by Robert3141** [comment]
Yeah I need to change the package versions as they're conflicting. Thanks for reminding me. You can use the older version

**Comment by Robert3141** [comment]
Hopefully V2.0.2 solves the problem. Feel free to reopen this issue if that is not the case
