### ISSUE TITLE
It doesnt´t work for me the "Usage on Android"

### ISSUE THREAD

**Issue by seel-channel** [Robert3141/client_server_lan#13]
# **I tried this but it doesn't work for me:**

In android/app/AndroidManifest

```xml
<application ...
  android:networkSecurityConfig="@xml/network_security_config" >

 <meta-data android:name="io.flutter.network-policy"
        android:resource="@xml/network_security_config"/>
```

Then create a folder xml inside create a file: network_security_config.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
     <trust-anchors>
        <certificates src="system" />
    </trust-anchors>
  </base-config>
 </network-security-config>
```

# **I replaced for that and works!**

Add  _usesCleartextTraffic_ in your **Android Manifest** file, located in `<project_root>/android/app/src/main/AndroidManifest.xml`

```xml
<manifest>
    <application android:usesCleartextTraffic="true">...</aplication>
</manifest>
```

PD: Works fine with 2 physical devices on network with internet connection, but when a create a Hospot in a device without internet connection the LAN communication doesn´t work anymore :C

**Comment by Robert3141** [comment]
I'm assuming the problem is with dio on the hotspot without a internet connection. However, i will look into this issue and see if i can solve it

**Comment by seel-channel** [comment]
Thanks! uwu

**Comment by fikrirazzaq** [comment]
It still works fine for me when I used hotspot with no internet access.

But I have an Android (Lenovo K520) that can't forward the broadcast (xxx.xxx.xxx.255) to another devices, but everything else (Start Server, Start Client,  Receive Data, Send Data) is fine. Not sure this problem from dio, another package, or the phone itself.

**Comment by seel-channel** [comment]
I've tested it only one time. I will test it with other and the same devices, and I'm going to tell you the updates :)

**Comment by Robert3141** [comment]
Haven't heard further problems so closing for now. Reopen if the problem persists
